### ISSUE TITLE
Please provide the slides used to teach in Intermediate module

### ISSUE THREAD

**Issue by Hasan-Mesbaul-Ali-Taher** [eftekhar-hossain/SKBI_Training#1]
On June 27, 2022  a slide on linear regression and logistic regression was used to teach the participants in intermediate module
On June 28, 2022  a slide on SVM and Neural net was used to teach the participants in intermediate module. Please provide these slides.

**Comment by eftekhar-hossain** [comment]
Uploaded. Please Check.

**Comment by Hasan-Mesbaul-Ali-Taher** [comment]
I have checked it. Thank you for your time and effort.
